export const tmpEmpData = [
  // {
  //   USER_ID: "dhyeon.kim",
  //   USER_NO: "20230808",
  //   USER_NM: "김동현D",
  //   TITLE_NM: "사원",
  //   DEPT_NM: "연구소/IT연구실",
  //   DEPT_CD: ""
  // },
  // {
  //   USER_ID: "dh.lee2",
  //   USER_NO: "20211201",
  //   USER_NM: "이덕현",
  //   TITLE_NM: "책임",
  //   DEPT_NM: "연구소/IT연구실"
  // },
  // {
  //   USER_ID: "jaehkim",
  //   USER_NO: "20160135",
  //   USER_NM: "김재희B",
  //   TITLE_NM: "선임",
  //   DEPT_NM: "연구소/IT연구실"
  // },
  {
    USER_NO: "20000102",
    USER_ID: "bonoo",
    USER_NM: "구본우",
    TITLE_NM: "수석",
    DEPT_CD: "D0410",
    DEPT_NM: "4부문",
  },
  {
    USER_NO: "20040115",
    USER_ID: "sunnyroad7",
    USER_NM: "신항선",
    TITLE_NM: "수석",
    DEPT_CD: "D0110",
    DEPT_NM: "1부문",
  },
  {
    USER_NO: "20050102",
    USER_ID: "slipperi",
    USER_NM: "윤철우",
    TITLE_NM: "소장",
    DEPT_CD: "D0110",
    DEPT_NM: "1부문",
  },
  {
    USER_NO: "20060108",
    USER_ID: "halki",
    USER_NM: "김기훈",
    TITLE_NM: "책임",
    DEPT_CD: "D0510",
    DEPT_NM: "5부문",
  },
  {
    USER_NO: "20061002",
    USER_ID: "jioim",
    USER_NM: "임지혁",
    TITLE_NM: "책임",
    DEPT_CD: "D0410",
    DEPT_NM: "4부문",
  },
  {
    USER_NO: "20061102",
    USER_ID: "yoolmn",
    USER_NM: "윤정희",
    TITLE_NM: "수석",
    DEPT_CD: "D0410",
    DEPT_NM: "4부문",
  },
  {
    USER_NO: "20071001",
    USER_ID: "yongarchi",
    USER_NM: "김준용",
    TITLE_NM: "책임",
    DEPT_CD: "D0510",
    DEPT_NM: "5부문",
  },
  {
    USER_NO: "20080106",
    USER_ID: "bjstyle",
    USER_NM: "김병준",
    TITLE_NM: "책임",
    DEPT_CD: "D0410",
    DEPT_NM: "4부문",
  },
  {
    USER_NO: "20080122",
    USER_ID: "guswjd99",
    USER_NM: "배현정",
    TITLE_NM: "책임",
    DEPT_CD: "D0110",
    DEPT_NM: "1부문",
  },
  {
    USER_NO: "20080303",
    USER_ID: "newstyner",
    USER_NM: "김용재",
    TITLE_NM: "수석",
    DEPT_CD: "D0110",
    DEPT_NM: "1부문",
  },
  {
    USER_NO: "20090115",
    USER_ID: "fjune",
    USER_NM: "신영준",
    TITLE_NM: "책임",
    DEPT_CD: "D0110",
    DEPT_NM: "1부문",
  },
  {
    USER_NO: "20120108",
    USER_ID: "cjpark",
    USER_NM: "박창준",
    TITLE_NM: "책임",
    DEPT_CD: "D0510",
    DEPT_NM: "5부문",
  },
  {
    USER_NO: "20120403",
    USER_ID: "jylim",
    USER_NM: "임지용",
    TITLE_NM: "책임",
    DEPT_CD: "D0110",
    DEPT_NM: "1부문",
  },
  {
    USER_NO: "20130116",
    USER_ID: "seongwoon",
    USER_NM: "이성운",
    TITLE_NM: "책임",
    DEPT_CD: "D0110",
    DEPT_NM: "1부문",
  },
  {
    USER_NO: "20130312",
    USER_ID: "ijkim",
    USER_NM: "김인주",
    TITLE_NM: "책임",
    DEPT_CD: "D0510",
    DEPT_NM: "5부문",
  },
  {
    USER_NO: "20131012",
    USER_ID: "mdh",
    USER_NM: "민대홍",
    TITLE_NM: "책임",
    DEPT_CD: "D0410",
    DEPT_NM: "4부문",
  },
  {
    USER_NO: "20140101",
    USER_ID: "kkangu",
    USER_NM: "강유진",
    TITLE_NM: "책임",
    DEPT_CD: "D0110",
    DEPT_NM: "1부문",
  },
  {
    USER_NO: "20140706",
    USER_ID: "dkkum",
    USER_NM: "금동윤",
    TITLE_NM: "책임",
    DEPT_CD: "D0110",
    DEPT_NM: "1부문",
  },
  {
    USER_NO: "20141007",
    USER_ID: "jihyenlee",
    USER_NM: "이지현",
    TITLE_NM: "책임",
    DEPT_CD: "D0410",
    DEPT_NM: "4부문",
  },
  {
    USER_NO: "20141010",
    USER_ID: "mdjang",
    USER_NM: "장선혜",
    TITLE_NM: "책임",
    DEPT_CD: "D0210",
    DEPT_NM: "2부문",
  },
  {
    USER_NO: "20141011",
    USER_ID: "imbh",
    USER_NM: "임범호",
    TITLE_NM: "책임",
    DEPT_CD: "D0310",
    DEPT_NM: "3부문",
  },
  {
    USER_NO: "20150109",
    USER_ID: "hjnam",
    USER_NM: "남혜진",
    TITLE_NM: "선임",
    DEPT_CD: "D0210",
    DEPT_NM: "2부문",
  },
  {
    USER_NO: "20150128",
    USER_ID: "jjwfly",
    USER_NM: "정지원",
    TITLE_NM: "선임",
    DEPT_CD: "D0510",
    DEPT_NM: "5부문",
  },
  {
    USER_NO: "20150131",
    USER_ID: "kschoi87",
    USER_NM: "최규석",
    TITLE_NM: "선임",
    DEPT_CD: "D0310",
    DEPT_NM: "3부문",
  },
  {
    USER_NO: "20150602",
    USER_ID: "kimjinhee",
    USER_NM: "김진희B",
    TITLE_NM: "책임",
    DEPT_CD: "D0510",
    DEPT_NM: "5부문",
  },
  {
    USER_NO: "20150705",
    USER_ID: "kbyoo",
    USER_NM: "유금빛",
    TITLE_NM: "책임",
    DEPT_CD: "D0110",
    DEPT_NM: "1부문",
  },
  {
    USER_NO: "20150805",
    USER_ID: "kdr",
    USER_NM: "김동립",
    TITLE_NM: "책임",
    DEPT_CD: "D0410",
    DEPT_NM: "4부문",
  },
  {
    USER_NO: "20150806",
    USER_ID: "mjh1000",
    USER_NM: "민정환",
    TITLE_NM: "책임",
    DEPT_CD: "D0410",
    DEPT_NM: "4부문",
  },
  {
    USER_NO: "20150807",
    USER_ID: "jongiry",
    USER_NM: "박종일",
    TITLE_NM: "책임",
    DEPT_CD: "D0310",
    DEPT_NM: "3부문",
  },
  {
    USER_NO: "20160108",
    USER_ID: "khskhskhs",
    USER_NM: "김형섭",
    TITLE_NM: "선임",
    DEPT_CD: "D0510",
    DEPT_NM: "5부문",
  },
  {
    USER_NO: "20160117",
    USER_ID: "gangarchi",
    USER_NM: "이경하",
    TITLE_NM: "선임",
    DEPT_CD: "D0410",
    DEPT_NM: "4부문",
  },
  {
    USER_NO: "20160138",
    USER_ID: "azikang",
    USER_NM: "강동우",
    TITLE_NM: "책임",
    DEPT_CD: "D0410",
    DEPT_NM: "4부문",
  },
  {
    USER_NO: "20160505",
    USER_ID: "jyh311",
    USER_NM: "주연홍",
    TITLE_NM: "책임",
    DEPT_CD: "D0210",
    DEPT_NM: "2부문",
  },
  {
    USER_NO: "20160901",
    USER_ID: "sh.jung",
    USER_NM: "정수희",
    TITLE_NM: "책임",
    DEPT_CD: "D0410",
    DEPT_NM: "4부문",
  },
  {
    USER_NO: "20161101",
    USER_ID: "kjhin",
    USER_NM: "진규환",
    TITLE_NM: "수석",
    DEPT_CD: "D0410",
    DEPT_NM: "4부문",
  },
  {
    USER_NO: "20161102",
    USER_ID: "jiminlee",
    USER_NM: "이지민B",
    TITLE_NM: "책임",
    DEPT_CD: "D0410",
    DEPT_NM: "4부문",
  },
  {
    USER_NO: "20170103",
    USER_ID: "kbest03",
    USER_NM: "김동문",
    TITLE_NM: "선임",
    DEPT_CD: "D0510",
    DEPT_NM: "5부문",
  },
  {
    USER_NO: "20170116",
    USER_ID: "tngus086",
    USER_NM: "박수현",
    TITLE_NM: "선임",
    DEPT_CD: "D0410",
    DEPT_NM: "4부문",
  },
  {
    USER_NO: "20170120",
    USER_ID: "www4503",
    USER_NM: "배소영",
    TITLE_NM: "선임",
    DEPT_CD: "D0110",
    DEPT_NM: "1부문",
  },
  {
    USER_NO: "20170128",
    USER_ID: "jungyr",
    USER_NM: "정유라",
    TITLE_NM: "선임",
    DEPT_CD: "D0110",
    DEPT_NM: "1부문",
  },
  {
    USER_NO: "20170402",
    USER_ID: "jh.kim2",
    USER_NM: "김종현B",
    TITLE_NM: "선임",
    DEPT_CD: "D0510",
    DEPT_NM: "5부문",
  },
  {
    USER_NO: "20170607",
    USER_ID: "yj.bae",
    USER_NM: "배영준",
    TITLE_NM: "책임",
    DEPT_CD: "D0310",
    DEPT_NM: "3부문",
  },
  {
    USER_NO: "20170615",
    USER_ID: "hr.park",
    USER_NM: "박해리",
    TITLE_NM: "책임",
    DEPT_CD: "D0110",
    DEPT_NM: "1부문",
  },
  {
    USER_NO: "20170704",
    USER_ID: "sj.cho",
    USER_NM: "조성진",
    TITLE_NM: "선임",
    DEPT_CD: "D0410",
    DEPT_NM: "4부문",
  },
  {
    USER_NO: "20171102",
    USER_ID: "mj.cho",
    USER_NM: "조명정",
    TITLE_NM: "선임",
    DEPT_CD: "D0410",
    DEPT_NM: "4부문",
  },
  {
    USER_NO: "20171104",
    USER_ID: "ke.lee",
    USER_NM: "이고은",
    TITLE_NM: "책임",
    DEPT_CD: "D0510",
    DEPT_NM: "5부문",
  },
  {
    USER_NO: "20180103",
    USER_ID: "sj.kwon",
    USER_NM: "권상진",
    TITLE_NM: "선임",
    DEPT_CD: "D0510",
    DEPT_NM: "5부문",
  },
  {
    USER_NO: "20180106",
    USER_ID: "th.kim",
    USER_NM: "김태형",
    TITLE_NM: "선임",
    DEPT_CD: "D0510",
    DEPT_NM: "5부문",
  },
  {
    USER_NO: "20180110",
    USER_ID: "hw.nam",
    USER_NM: "남혜우",
    TITLE_NM: "선임",
    DEPT_CD: "D0510",
    DEPT_NM: "5부문",
  },
  {
    USER_NO: "20180114",
    USER_ID: "jy.park",
    USER_NM: "박준영",
    TITLE_NM: "선임",
    DEPT_CD: "D0310",
    DEPT_NM: "3부문",
  },
  {
    USER_NO: "20180116",
    USER_ID: "jw.yang",
    USER_NM: "양재원",
    TITLE_NM: "선임",
    DEPT_CD: "D0110",
    DEPT_NM: "1부문",
  },
  {
    USER_NO: "20180124",
    USER_ID: "js.lee",
    USER_NM: "이종성",
    TITLE_NM: "선임",
    DEPT_CD: "D0410",
    DEPT_NM: "4부문",
  },
  {
    USER_NO: "20180137",
    USER_ID: "dh.kim2",
    USER_NM: "김대현",
    TITLE_NM: "책임",
    DEPT_CD: "D0410",
    DEPT_NM: "4부문",
  },
  {
    USER_NO: "20180138",
    USER_ID: "sj.yoon",
    USER_NM: "윤서진",
    TITLE_NM: "책임",
    DEPT_CD: "D0410",
    DEPT_NM: "4부문",
  },
  {
    USER_NO: "20180140",
    USER_ID: "sw.bang",
    USER_NM: "방세웅",
    TITLE_NM: "선임",
    DEPT_CD: "D0110",
    DEPT_NM: "1부문",
  },
  {
    USER_NO: "20180404",
    USER_ID: "hk.lee",
    USER_NM: "이현경B",
    TITLE_NM: "선임",
    DEPT_CD: "D0310",
    DEPT_NM: "3부문",
  },
  {
    USER_NO: "20180412",
    USER_ID: "yn.kim",
    USER_NM: "김유나",
    TITLE_NM: "선임",
    DEPT_CD: "D0310",
    DEPT_NM: "3부문",
  },
  {
    USER_NO: "20180416",
    USER_ID: "hj.kim5",
    USER_NM: "김현진F",
    TITLE_NM: "선임",
    DEPT_CD: "D0110",
    DEPT_NM: "1부문",
  },
  {
    USER_NO: "20180714",
    USER_ID: "dy.jung",
    USER_NM: "정다영",
    TITLE_NM: "선임",
    DEPT_CD: "D0210",
    DEPT_NM: "2부문",
  },
  {
    USER_NO: "20190101",
    USER_ID: "sj.kang",
    USER_NM: "강소진",
    TITLE_NM: "선임",
    DEPT_CD: "D0510",
    DEPT_NM: "5부문",
  },
  {
    USER_NO: "20190108",
    USER_ID: "jb.kim",
    USER_NM: "김재범",
    TITLE_NM: "선임",
    DEPT_CD: "D0210",
    DEPT_NM: "2부문",
  },
  {
    USER_NO: "20190109",
    USER_ID: "jh.kim4",
    USER_NM: "김주흔",
    TITLE_NM: "선임",
    DEPT_CD: "D0510",
    DEPT_NM: "5부문",
  },
  {
    USER_NO: "20190115",
    USER_ID: "mh.shin",
    USER_NM: "신문호",
    TITLE_NM: "선임",
    DEPT_CD: "D0210",
    DEPT_NM: "2부문",
  },
  {
    USER_NO: "20190116",
    USER_ID: "kb.yun",
    USER_NM: "윤기범",
    TITLE_NM: "선임",
    DEPT_CD: "D0410",
    DEPT_NM: "4부문",
  },
  {
    USER_NO: "20190123",
    USER_ID: "cw.chang",
    USER_NM: "장채원",
    TITLE_NM: "선임",
    DEPT_CD: "D0310",
    DEPT_NM: "3부문",
  },
  {
    USER_NO: "20190405",
    USER_ID: "jw.lee",
    USER_NM: "이준우",
    TITLE_NM: "선임",
    DEPT_CD: "D0310",
    DEPT_NM: "3부문",
  },
  {
    USER_NO: "20190414",
    USER_ID: "zy.han",
    USER_NM: "한지연",
    TITLE_NM: "책임",
    DEPT_CD: "D0510",
    DEPT_NM: "5부문",
  },
  {
    USER_NO: "20190503",
    USER_ID: "hj.song",
    USER_NM: "송효정",
    TITLE_NM: "책임",
    DEPT_CD: "D0510",
    DEPT_NM: "5부문",
  },
  {
    USER_NO: "20190604",
    USER_ID: "mh.gwak",
    USER_NM: "곽민환",
    TITLE_NM: "선임",
    DEPT_CD: "D0110",
    DEPT_NM: "1부문",
  },
  {
    USER_NO: "20190708",
    USER_ID: "sj.hong",
    USER_NM: "홍석종",
    TITLE_NM: "선임",
    DEPT_CD: "D0310",
    DEPT_NM: "3부문",
  },
  {
    USER_NO: "20190902",
    USER_ID: "yi.kim",
    USER_NM: "김영인",
    TITLE_NM: "책임",
    DEPT_CD: "D0510",
    DEPT_NM: "5부문",
  },
  {
    USER_NO: "20200109",
    USER_ID: "jho.kim",
    USER_NM: "김진호",
    TITLE_NM: "선임",
    DEPT_CD: "D0510",
    DEPT_NM: "5부문",
  },
  {
    USER_NO: "20200116",
    USER_ID: "sj.song",
    USER_NM: "송수정",
    TITLE_NM: "선임",
    DEPT_CD: "D0410",
    DEPT_NM: "4부문",
  },
  {
    USER_NO: "20200117",
    USER_ID: "jr.shim",
    USER_NM: "심정륜",
    TITLE_NM: "선임",
    DEPT_CD: "D0410",
    DEPT_NM: "4부문",
  },
  {
    USER_NO: "20200121",
    USER_ID: "hs.woo",
    USER_NM: "우현석",
    TITLE_NM: "선임",
    DEPT_CD: "D0210",
    DEPT_NM: "2부문",
  },
  {
    USER_NO: "20200124",
    USER_ID: "yk.lee",
    USER_NM: "이유경",
    TITLE_NM: "선임",
    DEPT_CD: "D0510",
    DEPT_NM: "5부문",
  },
  {
    USER_NO: "20200126",
    USER_ID: "hc.lee",
    USER_NM: "이현철B",
    TITLE_NM: "선임",
    DEPT_CD: "D0210",
    DEPT_NM: "2부문",
  },
  {
    USER_NO: "20200206",
    USER_ID: "jy.kim2",
    USER_NM: "김지영C",
    TITLE_NM: "선임",
    DEPT_CD: "D0110",
    DEPT_NM: "1부문",
  },
  {
    USER_NO: "20200406",
    USER_ID: "mk.choi",
    USER_NM: "최민경",
    TITLE_NM: "선임",
    DEPT_CD: "D0210",
    DEPT_NM: "2부문",
  },
  {
    USER_NO: "20200701",
    USER_ID: "jd.park",
    USER_NM: "박종덕",
    TITLE_NM: "책임",
    DEPT_CD: "D0210",
    DEPT_NM: "2부문",
  },
  {
    USER_NO: "20200704",
    USER_ID: "yh.na",
    USER_NM: "나영호",
    TITLE_NM: "책임",
    DEPT_CD: "D0510",
    DEPT_NM: "5부문",
  },
  {
    USER_NO: "20200806",
    USER_ID: "sc.kim",
    USER_NM: "김세찬",
    TITLE_NM: "책임",
    DEPT_CD: "D0410",
    DEPT_NM: "4부문",
  },
  {
    USER_NO: "20200808",
    USER_ID: "mj.byun",
    USER_NM: "변명진",
    TITLE_NM: "책임",
    DEPT_CD: "D0510",
    DEPT_NM: "5부문",
  },
  {
    USER_NO: "20200816",
    USER_ID: "sy.lee3",
    USER_NM: "이승용",
    TITLE_NM: "선임",
    DEPT_CD: "D0410",
    DEPT_NM: "4부문",
  },
  {
    USER_NO: "20201004",
    USER_ID: "ws.kim",
    USER_NM: "김우석",
    TITLE_NM: "책임",
    DEPT_CD: "D0210",
    DEPT_NM: "2부문",
  },
  {
    USER_NO: "20201202",
    USER_ID: "dhee.kim",
    USER_NM: "김도희",
    TITLE_NM: "선임",
    DEPT_CD: "D0510",
    DEPT_NM: "5부문",
  },
  {
    USER_NO: "20201208",
    USER_ID: "em.kim",
    USER_NM: "김은미B",
    TITLE_NM: "책임",
    DEPT_CD: "D0210",
    DEPT_NM: "2부문",
  },
  {
    USER_NO: "20210102",
    USER_ID: "sm.kang",
    USER_NM: "강석민",
    TITLE_NM: "사원",
    DEPT_CD: "D0110",
    DEPT_NM: "1부문",
  },
  {
    USER_NO: "20210109",
    USER_ID: "ej.kim4",
    USER_NM: "김은정B",
    TITLE_NM: "사원",
    DEPT_CD: "D0510",
    DEPT_NM: "5부문",
  },
  {
    USER_NO: "20210110",
    USER_ID: "jy.kim3",
    USER_NM: "김제연",
    TITLE_NM: "사원",
    DEPT_CD: "D0410",
    DEPT_NM: "4부문",
  },
  {
    USER_NO: "20210111",
    USER_ID: "je.kim",
    USER_NM: "김지을",
    TITLE_NM: "사원",
    DEPT_CD: "D0410",
    DEPT_NM: "4부문",
  },
  {
    USER_NO: "20210112",
    USER_ID: "mh.park",
    USER_NM: "박민희",
    TITLE_NM: "사원",
    DEPT_CD: "D0510",
    DEPT_NM: "5부문",
  },
  {
    USER_NO: "20210115",
    USER_ID: "yj.park",
    USER_NM: "박유진",
    TITLE_NM: "사원",
    DEPT_CD: "D0210",
    DEPT_NM: "2부문",
  },
  {
    USER_NO: "20210116",
    USER_ID: "jk.park",
    USER_NM: "박재균",
    TITLE_NM: "사원",
    DEPT_CD: "D0510",
    DEPT_NM: "5부문",
  },
  {
    USER_NO: "20210117",
    USER_ID: "jy.park4",
    USER_NM: "박준용",
    TITLE_NM: "사원",
    DEPT_CD: "D0110",
    DEPT_NM: "1부문",
  },
  {
    USER_NO: "20210118",
    USER_ID: "jh.park4",
    USER_NM: "박준호",
    TITLE_NM: "사원",
    DEPT_CD: "D0210",
    DEPT_NM: "2부문",
  },
  {
    USER_NO: "20210119",
    USER_ID: "iy.paik",
    USER_NM: "백인엽",
    TITLE_NM: "사원",
    DEPT_CD: "D0510",
    DEPT_NM: "5부문",
  },
  {
    USER_NO: "20210122",
    USER_ID: "hb.soon",
    USER_NM: "순현범",
    TITLE_NM: "사원",
    DEPT_CD: "D0210",
    DEPT_NM: "2부문",
  },
  {
    USER_NO: "20210123",
    USER_ID: "gy.sim",
    USER_NM: "심가영",
    TITLE_NM: "사원",
    DEPT_CD: "D0110",
    DEPT_NM: "1부문",
  },
  {
    USER_NO: "20210124",
    USER_ID: "hb.yang",
    USER_NM: "양홍범",
    TITLE_NM: "사원",
    DEPT_CD: "D0110",
    DEPT_NM: "1부문",
  },
  {
    USER_NO: "20210132",
    USER_ID: "jhyun.lee",
    USER_NM: "이지현C",
    TITLE_NM: "사원",
    DEPT_CD: "D0210",
    DEPT_NM: "2부문",
  },
  {
    USER_NO: "20210133",
    USER_ID: "jw.jang",
    USER_NM: "장제환",
    TITLE_NM: "사원",
    DEPT_CD: "D0110",
    DEPT_NM: "1부문",
  },
  {
    USER_NO: "20210137",
    USER_ID: "hl.jung",
    USER_NM: "정하림",
    TITLE_NM: "사원",
    DEPT_CD: "D0510",
    DEPT_NM: "5부문",
  },
  {
    USER_NO: "20210140",
    USER_ID: "ms.choi",
    USER_NM: "최민승",
    TITLE_NM: "사원",
    DEPT_CD: "D0410",
    DEPT_NM: "4부문",
  },
  {
    USER_NO: "20210141",
    USER_ID: "sh.choi2",
    USER_NM: "최승호",
    TITLE_NM: "사원",
    DEPT_CD: "D0110",
    DEPT_NM: "1부문",
  },
  {
    USER_NO: "20210143",
    USER_ID: "hy.hyun",
    USER_NM: "현하영",
    TITLE_NM: "사원",
    DEPT_CD: "D0410",
    DEPT_NM: "4부문",
  },
  {
    USER_NO: "20210160",
    USER_ID: "yjae.kim",
    USER_NM: "김윤재",
    TITLE_NM: "선임",
    DEPT_CD: "D0510",
    DEPT_NM: "5부문",
  },
  {
    USER_NO: "20210416",
    USER_ID: "ys.jin",
    USER_NM: "진윤식",
    TITLE_NM: "선임",
    DEPT_CD: "D0110",
    DEPT_NM: "1부문",
  },
  {
    USER_NO: "20210509",
    USER_ID: "cs.park2",
    USER_NM: "박천성",
    TITLE_NM: "책임",
    DEPT_CD: "D0210",
    DEPT_NM: "2부문",
  },
  {
    USER_NO: "20210513",
    USER_ID: "sh.kim2",
    USER_NM: "김성희",
    TITLE_NM: "책임",
    DEPT_CD: "D0510",
    DEPT_NM: "5부문",
  },
  {
    USER_NO: "20210517",
    USER_ID: "tk.kim",
    USER_NM: "김태균B",
    TITLE_NM: "책임",
    DEPT_CD: "D0110",
    DEPT_NM: "1부문",
  },
  {
    USER_NO: "20210601",
    USER_ID: "sh.hong",
    USER_NM: "홍상현",
    TITLE_NM: "책임",
    DEPT_CD: "D0110",
    DEPT_NM: "1부문",
  },
  {
    USER_NO: "20210618",
    USER_ID: "shyeon.lee",
    USER_NM: "이수현C",
    TITLE_NM: "선임",
    DEPT_CD: "D0310",
    DEPT_NM: "3부문",
  },
  {
    USER_NO: "20210621",
    USER_ID: "rr.yang",
    USER_NM: "양리라",
    TITLE_NM: "책임",
    DEPT_CD: "D0510",
    DEPT_NM: "5부문",
  },
  {
    USER_NO: "20210627",
    USER_ID: "dy.kim2",
    USER_NM: "김동엽",
    TITLE_NM: "선임",
    DEPT_CD: "D0410",
    DEPT_NM: "4부문",
  },
  {
    USER_NO: "20210701",
    USER_ID: "cg.lee",
    USER_NM: "이창근",
    TITLE_NM: "선임",
    DEPT_CD: "D0110",
    DEPT_NM: "1부문",
  },
  {
    USER_NO: "20210714",
    USER_ID: "sm.choi2",
    USER_NM: "최성민B",
    TITLE_NM: "선임",
    DEPT_CD: "D0310",
    DEPT_NM: "3부문",
  },
  {
    USER_NO: "20210723",
    USER_ID: "jy.oh2",
    USER_NM: "오진영",
    TITLE_NM: "선임",
    DEPT_CD: "D0410",
    DEPT_NM: "4부문",
  },
  {
    USER_NO: "20210806",
    USER_ID: "tm.lee",
    USER_NM: "이태민",
    TITLE_NM: "선임",
    DEPT_CD: "D0110",
    DEPT_NM: "1부문",
  },
  {
    USER_NO: "20210807",
    USER_ID: "jw.joo",
    USER_NM: "주재원",
    TITLE_NM: "선임",
    DEPT_CD: "D0110",
    DEPT_NM: "1부문",
  },
  {
    USER_NO: "20210808",
    USER_ID: "jh.byeon",
    USER_NM: "변정희",
    TITLE_NM: "선임",
    DEPT_CD: "D0210",
    DEPT_NM: "2부문",
  },
  {
    USER_NO: "20210809",
    USER_ID: "ma.choi",
    USER_NM: "최미애",
    TITLE_NM: "선임",
    DEPT_CD: "D0210",
    DEPT_NM: "2부문",
  },
  {
    USER_NO: "20210812",
    USER_ID: "mjin.lee",
    USER_NM: "이명진",
    TITLE_NM: "선임",
    DEPT_CD: "D0410",
    DEPT_NM: "4부문",
  },
  {
    USER_NO: "20210815",
    USER_ID: "yr.do",
    USER_NM: "도예린",
    TITLE_NM: "선임",
    DEPT_CD: "D0510",
    DEPT_NM: "5부문",
  },
  {
    USER_NO: "20210816",
    USER_ID: "yjoo.lee",
    USER_NM: "이용주",
    TITLE_NM: "선임",
    DEPT_CD: "D0510",
    DEPT_NM: "5부문",
  },
  {
    USER_NO: "20210823",
    USER_ID: "ny.kim2",
    USER_NM: "김나윤",
    TITLE_NM: "사원",
    DEPT_CD: "D0210",
    DEPT_NM: "2부문",
  },
  {
    USER_NO: "20210831",
    USER_ID: "ej.jang",
    USER_NM: "장은지",
    TITLE_NM: "선임",
    DEPT_CD: "D0110",
    DEPT_NM: "1부문",
  },
  {
    USER_NO: "20210832",
    USER_ID: "j.song",
    USER_NM: "송걸",
    TITLE_NM: "선임",
    DEPT_CD: "D0110",
    DEPT_NM: "1부문",
  },
  {
    USER_NO: "20210833",
    USER_ID: "jb.oh",
    USER_NM: "오정빈",
    TITLE_NM: "선임",
    DEPT_CD: "D0210",
    DEPT_NM: "2부문",
  },
  {
    USER_NO: "20210842",
    USER_ID: "sh.jeon",
    USER_NM: "전성희",
    TITLE_NM: "선임",
    DEPT_CD: "D0210",
    DEPT_NM: "2부문",
  },
  {
    USER_NO: "20210843",
    USER_ID: "yh.lee",
    USER_NM: "이유현",
    TITLE_NM: "선임",
    DEPT_CD: "D0310",
    DEPT_NM: "3부문",
  },
  {
    USER_NO: "20210844",
    USER_ID: "sh.yoo2",
    USER_NM: "유상훈",
    TITLE_NM: "책임",
    DEPT_CD: "D0410",
    DEPT_NM: "4부문",
  },
  {
    USER_NO: "20210846",
    USER_ID: "sm.han",
    USER_NM: "한선미",
    TITLE_NM: "선임",
    DEPT_CD: "D0410",
    DEPT_NM: "4부문",
  },
  {
    USER_NO: "20210847",
    USER_ID: "js.ham",
    USER_NM: "함지승",
    TITLE_NM: "선임",
    DEPT_CD: "D0410",
    DEPT_NM: "4부문",
  },
  {
    USER_NO: "20210901",
    USER_ID: "ma.lee",
    USER_NM: "이민아",
    TITLE_NM: "선임",
    DEPT_CD: "D0110",
    DEPT_NM: "1부문",
  },
  {
    USER_NO: "20210902",
    USER_ID: "mb.kim",
    USER_NM: "김민봉",
    TITLE_NM: "책임",
    DEPT_CD: "D0210",
    DEPT_NM: "2부문",
  },
  {
    USER_NO: "20210911",
    USER_ID: "js.heo",
    USER_NM: "허지선",
    TITLE_NM: "선임",
    DEPT_CD: "D0410",
    DEPT_NM: "4부문",
  },
  {
    USER_NO: "20211010",
    USER_ID: "jh.koo",
    USER_NM: "구자현",
    TITLE_NM: "선임",
    DEPT_CD: "D0110",
    DEPT_NM: "1부문",
  },
  {
    USER_NO: "20211012",
    USER_ID: "hsae.lee",
    USER_NM: "이한새",
    TITLE_NM: "선임",
    DEPT_CD: "D0310",
    DEPT_NM: "3부문",
  },
  {
    USER_NO: "20211024",
    USER_ID: "ig.joo",
    USER_NM: "주인규",
    TITLE_NM: "선임",
    DEPT_CD: "D0410",
    DEPT_NM: "4부문",
  },
  {
    USER_NO: "20211101",
    USER_ID: "yl.kim",
    USER_NM: "김용래",
    TITLE_NM: "선임",
    DEPT_CD: "D0510",
    DEPT_NM: "5부문",
  },
  {
    USER_NO: "20211110",
    USER_ID: "yhun.kim",
    USER_NM: "김용훈B",
    TITLE_NM: "선임",
    DEPT_CD: "D0210",
    DEPT_NM: "2부문",
  },
  {
    USER_NO: "20211115",
    USER_ID: "sh.han",
    USER_NM: "한승훈",
    TITLE_NM: "선임",
    DEPT_CD: "D0310",
    DEPT_NM: "3부문",
  },
  {
    USER_NO: "20211124",
    USER_ID: "ih.lee",
    USER_NM: "이인혁",
    TITLE_NM: "선임",
    DEPT_CD: "D0210",
    DEPT_NM: "2부문",
  },
  {
    USER_NO: "20211126",
    USER_ID: "sju.kim",
    USER_NM: "김선주B",
    TITLE_NM: "선임",
    DEPT_CD: "D0510",
    DEPT_NM: "5부문",
  },
  {
    USER_NO: "20211207",
    USER_ID: "mg.park2",
    USER_NM: "박민규B",
    TITLE_NM: "선임",
    DEPT_CD: "D0410",
    DEPT_NM: "4부문",
  },
  {
    USER_NO: "20211208",
    USER_ID: "yn.shin",
    USER_NM: "신유나",
    TITLE_NM: "선임",
    DEPT_CD: "D0510",
    DEPT_NM: "5부문",
  },
  {
    USER_NO: "20211209",
    USER_ID: "hs.kim4",
    USER_NM: "김해수",
    TITLE_NM: "책임",
    DEPT_CD: "D0510",
    DEPT_NM: "5부문",
  },
  {
    USER_NO: "20220103",
    USER_ID: "es.kwon",
    USER_NM: "권은서",
    TITLE_NM: "사원",
    DEPT_CD: "D0210",
    DEPT_NM: "2부문",
  },
  {
    USER_NO: "20220104",
    USER_ID: "jh.gwon",
    USER_NM: "권재희",
    TITLE_NM: "사원",
    DEPT_CD: "D0510",
    DEPT_NM: "5부문",
  },
  {
    USER_NO: "20220109",
    USER_ID: "hju.kim2",
    USER_NM: "김효주",
    TITLE_NM: "사원",
    DEPT_CD: "D0110",
    DEPT_NM: "1부문",
  },
  {
    USER_NO: "20220110",
    USER_ID: "so.roh",
    USER_NM: "노승욱",
    TITLE_NM: "사원",
    DEPT_CD: "D0510",
    DEPT_NM: "5부문",
  },
  {
    USER_NO: "20220111",
    USER_ID: "sr.moon",
    USER_NM: "문서령",
    TITLE_NM: "사원",
    DEPT_CD: "D0110",
    DEPT_NM: "1부문",
  },
  {
    USER_NO: "20220112",
    USER_ID: "je.park4",
    USER_NM: "박정은B",
    TITLE_NM: "사원",
    DEPT_CD: "D0210",
    DEPT_NM: "2부문",
  },
  {
    USER_NO: "20220113",
    USER_ID: "jseok.park",
    USER_NM: "박준석B",
    TITLE_NM: "사원",
    DEPT_CD: "D0210",
    DEPT_NM: "2부문",
  },
  {
    USER_NO: "20220114",
    USER_ID: "jw.park2",
    USER_NM: "박지우",
    TITLE_NM: "사원",
    DEPT_CD: "D0310",
    DEPT_NM: "3부문",
  },
  {
    USER_NO: "20220115",
    USER_ID: "ji.park",
    USER_NM: "박지해",
    TITLE_NM: "사원",
    DEPT_CD: "D0410",
    DEPT_NM: "4부문",
  },
  {
    USER_NO: "20220116",
    USER_ID: "mg.bae",
    USER_NM: "배민건",
    TITLE_NM: "사원",
    DEPT_CD: "D0410",
    DEPT_NM: "4부문",
  },
  {
    USER_NO: "20220117",
    USER_ID: "jm.baek",
    USER_NM: "백재민",
    TITLE_NM: "사원",
    DEPT_CD: "D0210",
    DEPT_NM: "2부문",
  },
  {
    USER_NO: "20220118",
    USER_ID: "yw.byun",
    USER_NM: "변영우",
    TITLE_NM: "사원",
    DEPT_CD: "D0110",
    DEPT_NM: "1부문",
  },
  {
    USER_NO: "20220119",
    USER_ID: "hy.sohn",
    USER_NM: "손효주",
    TITLE_NM: "사원",
    DEPT_CD: "D0210",
    DEPT_NM: "2부문",
  },
  {
    USER_NO: "20220121",
    USER_ID: "he.yang",
    USER_NM: "양희은",
    TITLE_NM: "사원",
    DEPT_CD: "D0510",
    DEPT_NM: "5부문",
  },
  {
    USER_NO: "20220124",
    USER_ID: "dw.lee4",
    USER_NM: "이동원B",
    TITLE_NM: "사원",
    DEPT_CD: "D0310",
    DEPT_NM: "3부문",
  },
  {
    USER_NO: "20220125",
    USER_ID: "shyun.lee",
    USER_NM: "이승현B",
    TITLE_NM: "사원",
    DEPT_CD: "D0410",
    DEPT_NM: "4부문",
  },
  {
    USER_NO: "20220127",
    USER_ID: "jhyeon.lee",
    USER_NM: "이재현B",
    TITLE_NM: "사원",
    DEPT_CD: "D0510",
    DEPT_NM: "5부문",
  },
  {
    USER_NO: "20220128",
    USER_ID: "c.lee",
    USER_NM: "이창",
    TITLE_NM: "사원",
    DEPT_CD: "D0110",
    DEPT_NM: "1부문",
  },
  {
    USER_NO: "20220135",
    USER_ID: "jh.jeon",
    USER_NM: "전준현",
    TITLE_NM: "사원",
    DEPT_CD: "D0210",
    DEPT_NM: "2부문",
  },
  {
    USER_NO: "20220138",
    USER_ID: "ys.jee",
    USER_NM: "지영선",
    TITLE_NM: "사원",
    DEPT_CD: "D0110",
    DEPT_NM: "1부문",
  },
  {
    USER_NO: "20220140",
    USER_ID: "js.choi",
    USER_NM: "최정식",
    TITLE_NM: "사원",
    DEPT_CD: "D0310",
    DEPT_NM: "3부문",
  },
  {
    USER_NO: "20220209",
    USER_ID: "sk.ryu",
    USER_NM: "류수경",
    TITLE_NM: "선임",
    DEPT_CD: "D0510",
    DEPT_NM: "5부문",
  },
  {
    USER_NO: "20220313",
    USER_ID: "shee.lee",
    USER_NM: "이세희",
    TITLE_NM: "선임",
    DEPT_CD: "D0310",
    DEPT_NM: "3부문",
  },
  {
    USER_NO: "20220405",
    USER_ID: "kj.kim",
    USER_NM: "김교진",
    TITLE_NM: "수석",
    DEPT_CD: "D0310",
    DEPT_NM: "3부문",
  },
  {
    USER_NO: "20220414",
    USER_ID: "br.na",
    USER_NM: "나병록",
    TITLE_NM: "선임",
    DEPT_CD: "D0110",
    DEPT_NM: "1부문",
  },
  {
    USER_NO: "20220502",
    USER_ID: "sh.kang2",
    USER_NM: "강석하",
    TITLE_NM: "선임",
    DEPT_CD: "D0210",
    DEPT_NM: "2부문",
  },
  {
    USER_NO: "20220503",
    USER_ID: "sg.ko",
    USER_NM: "고상균",
    TITLE_NM: "선임",
    DEPT_CD: "D0510",
    DEPT_NM: "5부문",
  },
  {
    USER_NO: "20220515",
    USER_ID: "jhye.kim2",
    USER_NM: "김지혜C",
    TITLE_NM: "선임",
    DEPT_CD: "D0410",
    DEPT_NM: "4부문",
  },
  {
    USER_NO: "20220518",
    USER_ID: "sm.lee",
    USER_NM: "이수민",
    TITLE_NM: "선임",
    DEPT_CD: "D0210",
    DEPT_NM: "2부문",
  },
  {
    USER_NO: "20220601",
    USER_ID: "sme.kwon",
    USER_NM: "권사무엘",
    TITLE_NM: "책임",
    DEPT_CD: "D0210",
    DEPT_NM: "2부문",
  },
  {
    USER_NO: "20220605",
    USER_ID: "yo.kim",
    USER_NM: "김여운",
    TITLE_NM: "선임",
    DEPT_CD: "D0210",
    DEPT_NM: "2부문",
  },
  {
    USER_NO: "20220606",
    USER_ID: "hr.ryu",
    USER_NM: "유희라",
    TITLE_NM: "선임",
    DEPT_CD: "D0110",
    DEPT_NM: "1부문",
  },
  {
    USER_NO: "20220607",
    USER_ID: "ms.kim4",
    USER_NM: "김민석B",
    TITLE_NM: "선임",
    DEPT_CD: "D0410",
    DEPT_NM: "4부문",
  },
  {
    USER_NO: "20220703",
    USER_ID: "nk.lee",
    USER_NM: "이나경",
    TITLE_NM: "선임",
    DEPT_CD: "D0510",
    DEPT_NM: "5부문",
  },
  {
    USER_NO: "20220704",
    USER_ID: "yi.lee",
    USER_NM: "이영인",
    TITLE_NM: "선임",
    DEPT_CD: "D0110",
    DEPT_NM: "1부문",
  },
  {
    USER_NO: "20220708",
    USER_ID: "dk.na",
    USER_NM: "나동균",
    TITLE_NM: "선임",
    DEPT_CD: "D0510",
    DEPT_NM: "5부문",
  },
  {
    USER_NO: "20220714",
    USER_ID: "dy.kim4",
    USER_NM: "김대윤",
    TITLE_NM: "선임",
    DEPT_CD: "D0410",
    DEPT_NM: "4부문",
  },
  {
    USER_NO: "20220719",
    USER_ID: "gh.eom",
    USER_NM: "엄기현",
    TITLE_NM: "선임",
    DEPT_CD: "D0410",
    DEPT_NM: "4부문",
  },
  {
    USER_NO: "20220720",
    USER_ID: "ys.park2",
    USER_NM: "박윤선",
    TITLE_NM: "선임",
    DEPT_CD: "D0510",
    DEPT_NM: "5부문",
  },
  {
    USER_NO: "20220805",
    USER_ID: "jyoung.park",
    USER_NM: "박주영C",
    TITLE_NM: "선임",
    DEPT_CD: "D0510",
    DEPT_NM: "5부문",
  },
  {
    USER_NO: "20220808",
    USER_ID: "ds.kim",
    USER_NM: "김동수B",
    TITLE_NM: "선임",
    DEPT_CD: "D0110",
    DEPT_NM: "1부문",
  },
  {
    USER_NO: "20220809",
    USER_ID: "mb.kim2",
    USER_NM: "김민비",
    TITLE_NM: "선임",
    DEPT_CD: "D0510",
    DEPT_NM: "5부문",
  },
  {
    USER_NO: "20220810",
    USER_ID: "yh.lee4",
    USER_NM: "이영현",
    TITLE_NM: "선임",
    DEPT_CD: "D0510",
    DEPT_NM: "5부문",
  },
  {
    USER_NO: "20220814",
    USER_ID: "he.kim",
    USER_NM: "김효언",
    TITLE_NM: "선임",
    DEPT_CD: "D0510",
    DEPT_NM: "5부문",
  },
  {
    USER_NO: "20220817",
    USER_ID: "sg.lee",
    USER_NM: "이선규",
    TITLE_NM: "선임",
    DEPT_CD: "D0510",
    DEPT_NM: "5부문",
  },
  {
    USER_NO: "20220901",
    USER_ID: "sm.lee2",
    USER_NM: "이수민B",
    TITLE_NM: "선임",
    DEPT_CD: "D0110",
    DEPT_NM: "1부문",
  },
  {
    USER_NO: "20220905",
    USER_ID: "gc.heo",
    USER_NM: "허근창",
    TITLE_NM: "선임",
    DEPT_CD: "D0210",
    DEPT_NM: "2부문",
  },
  {
    USER_NO: "20220911",
    USER_ID: "dwon.lee",
    USER_NM: "이동원C",
    TITLE_NM: "사원",
    DEPT_CD: "D0510",
    DEPT_NM: "5부문",
  },
  {
    USER_NO: "20220913",
    USER_ID: "hy.lim",
    USER_NM: "임화련",
    TITLE_NM: "선임",
    DEPT_CD: "D0210",
    DEPT_NM: "2부문",
  },
  {
    USER_NO: "20220917",
    USER_ID: "jw.lee3",
    USER_NM: "이진우B",
    TITLE_NM: "선임",
    DEPT_CD: "D0410",
    DEPT_NM: "4부문",
  },
  {
    USER_NO: "20220920",
    USER_ID: "sn.kang",
    USER_NM: "강순녕",
    TITLE_NM: "선임",
    DEPT_CD: "D0110",
    DEPT_NM: "1부문",
  },
  {
    USER_NO: "20220921",
    USER_ID: "mh.park2",
    USER_NM: "박명환",
    TITLE_NM: "선임",
    DEPT_CD: "D0510",
    DEPT_NM: "5부문",
  },
  {
    USER_NO: "20221002",
    USER_ID: "syong.park",
    USER_NM: "박선용",
    TITLE_NM: "선임",
    DEPT_CD: "D0510",
    DEPT_NM: "5부문",
  },
  {
    USER_NO: "20221003",
    USER_ID: "jy.kang",
    USER_NM: "강재영",
    TITLE_NM: "선임",
    DEPT_CD: "D0510",
    DEPT_NM: "5부문",
  },
  {
    USER_NO: "20221013",
    USER_ID: "sy.yoo",
    USER_NM: "유서연B",
    TITLE_NM: "선임",
    DEPT_CD: "D0510",
    DEPT_NM: "5부문",
  },
  {
    USER_NO: "20221015",
    USER_ID: "cs.yang",
    USER_NM: "양창석",
    TITLE_NM: "선임",
    DEPT_CD: "D0110",
    DEPT_NM: "1부문",
  },
  {
    USER_NO: "20221016",
    USER_ID: "sg.son",
    USER_NM: "손수금",
    TITLE_NM: "선임",
    DEPT_CD: "D0510",
    DEPT_NM: "5부문",
  },
  {
    USER_NO: "20221022",
    USER_ID: "hs.kim3",
    USER_NM: "김현수",
    TITLE_NM: "선임",
    DEPT_CD: "D0510",
    DEPT_NM: "5부문",
  },
  {
    USER_NO: "20221026",
    USER_ID: "hr.kim",
    USER_NM: "김혜린B",
    TITLE_NM: "선임",
    DEPT_CD: "D0510",
    DEPT_NM: "5부문",
  },
  {
    USER_NO: "20221101",
    USER_ID: "hs.yun",
    USER_NM: "윤해성",
    TITLE_NM: "선임",
    DEPT_CD: "D0510",
    DEPT_NM: "5부문",
  },
  {
    USER_NO: "20221102",
    USER_ID: "sh.kwon2",
    USER_NM: "권승혁",
    TITLE_NM: "선임",
    DEPT_CD: "D0510",
    DEPT_NM: "5부문",
  },
  {
    USER_NO: "20221110",
    USER_ID: "yc.ro",
    USER_NM: "노영찬",
    TITLE_NM: "선임",
    DEPT_CD: "D0510",
    DEPT_NM: "5부문",
  },
  {
    USER_NO: "20221204",
    USER_ID: "sjung.lee",
    USER_NM: "이소정",
    TITLE_NM: "선임",
    DEPT_CD: "D0510",
    DEPT_NM: "5부문",
  },
  {
    USER_NO: "20230103",
    USER_ID: "yj.kwak",
    USER_NM: "곽예진",
    TITLE_NM: "사원",
    DEPT_CD: "D0510",
    DEPT_NM: "5부문",
  },
  {
    USER_NO: "20230104",
    USER_ID: "nh.kwon",
    USER_NM: "권남형",
    TITLE_NM: "사원",
    DEPT_CD: "D0210",
    DEPT_NM: "2부문",
  },
  {
    USER_NO: "20230107",
    USER_ID: "sa.kim",
    USER_NM: "김수안",
    TITLE_NM: "사원",
    DEPT_CD: "D0310",
    DEPT_NM: "3부문",
  },
  {
    USER_NO: "20230108",
    USER_ID: "yseul.kim",
    USER_NM: "김예슬",
    TITLE_NM: "사원",
    DEPT_CD: "D0210",
    DEPT_NM: "2부문",
  },
  {
    USER_NO: "20230114",
    USER_ID: "sb.moon",
    USER_NM: "문수빈",
    TITLE_NM: "사원",
    DEPT_CD: "D0110",
    DEPT_NM: "1부문",
  },
  {
    USER_NO: "20230115",
    USER_ID: "jh.moon",
    USER_NM: "문지희",
    TITLE_NM: "사원",
    DEPT_CD: "D0210",
    DEPT_NM: "2부문",
  },
  {
    USER_NO: "20230118",
    USER_ID: "jw.park3",
    USER_NM: "박준휘",
    TITLE_NM: "사원",
    DEPT_CD: "D0110",
    DEPT_NM: "1부문",
  },
  {
    USER_NO: "20230123",
    USER_ID: "sj.seok",
    USER_NM: "석수진",
    TITLE_NM: "사원",
    DEPT_CD: "D0510",
    DEPT_NM: "5부문",
  },
  {
    USER_NO: "20230125",
    USER_ID: "hc.song",
    USER_NM: "송현채",
    TITLE_NM: "사원",
    DEPT_CD: "D0510",
    DEPT_NM: "5부문",
  },
  {
    USER_NO: "20230126",
    USER_ID: "hc.shin",
    USER_NM: "신한찬",
    TITLE_NM: "사원",
    DEPT_CD: "D0210",
    DEPT_NM: "2부문",
  },
  {
    USER_NO: "20230132",
    USER_ID: "jh.yun",
    USER_NM: "윤준하",
    TITLE_NM: "사원",
    DEPT_CD: "D0210",
    DEPT_NM: "2부문",
  },
  {
    USER_NO: "20230134",
    USER_ID: "jm.lee3",
    USER_NM: "이재민",
    TITLE_NM: "사원",
    DEPT_CD: "D0110",
    DEPT_NM: "1부문",
  },
  {
    USER_NO: "20230135",
    USER_ID: "jp.lee",
    USER_NM: "이종평",
    TITLE_NM: "사원",
    DEPT_CD: "D0210",
    DEPT_NM: "2부문",
  },
  {
    USER_NO: "20230136",
    USER_ID: "je.lee3",
    USER_NM: "이지은D",
    TITLE_NM: "사원",
    DEPT_CD: "D0410",
    DEPT_NM: "4부문",
  },
  {
    USER_NO: "20230140",
    USER_ID: "sy.jeon3",
    USER_NM: "전승윤",
    TITLE_NM: "사원",
    DEPT_CD: "D0510",
    DEPT_NM: "5부문",
  },
  {
    USER_NO: "20230141",
    USER_ID: "sy.jung",
    USER_NM: "정세영",
    TITLE_NM: "사원",
    DEPT_CD: "D0510",
    DEPT_NM: "5부문",
  },
  {
    USER_NO: "20230143",
    USER_ID: "hm.chung",
    USER_NM: "정혜명",
    TITLE_NM: "사원",
    DEPT_CD: "D0410",
    DEPT_NM: "4부문",
  },
  {
    USER_NO: "20230144",
    USER_ID: "mh.cho",
    USER_NM: "조명훈",
    TITLE_NM: "사원",
    DEPT_CD: "D0110",
    DEPT_NM: "1부문",
  },
  {
    USER_NO: "20230152",
    USER_ID: "sh.hwang3",
    USER_NM: "황석훈",
    TITLE_NM: "사원",
    DEPT_CD: "D0410",
    DEPT_NM: "4부문",
  },
];

export const tmpDept = [
  { key: "D0000", text: "직원명 직접입력" },
  { key: "D0110", text: "1부문" },
  { key: "D0210", text: "2부문" },
  { key: "D0310", text: "3부문" },
  { key: "D0410", text: "4부문" },
  { key: "D0510", text: "5부문" },
  { key: "D0610", text: "기획부문" },
];

export const selectDeptData = [
  { value: null, label: "전체" },
  { value: "D0110", label: "1부문" },
  { value: "D0210", label: "2부문" },
  { value: "D0310", label: "3부문" },
  { value: "D0410", label: "4부문" },
  { value: "D0510", label: "5부문" },
  // { value: "D0610", label: "기타부서" },
];
